# pyproject.toml
[tool.black]
line-length = 120
target-version = ["py312"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]
ignore = []

# only ignore long lines in (HTML/JS strings)
per-file-ignores = { "campaign_money_graphs.py" = ["E501"] }
