name: Auto-fix Lint / format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write  # allow the bot to push formatting fixes

jobs:
  autofix:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dev tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.6.1 black==24.8.0

      - name: Run Ruff (auto-fix)
        run: |
          ruff check . --fix

      - name: Run Black (auto-format)
        run: |
          black .

      - name: Commit and push changes (if any)
        run: |
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore: apply auto-fixes (ruff/black)"
            git push
          fi
