name: CI / lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dev tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.6.1 black==24.8.0

      - name: Ruff (check)
        run: |
          ruff check . --output-format=github

      - name: Black (check)
        run: |
          black --check .
          
